<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Service;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Seeder cho các dịch vụ du lịch của các tỉnh
     */
    public function run(): void
    {
        // Dữ liệu du lịch - Gộp tất cả các tỉnh
        $services = [
            // Miền Bắc - Sơn La (province_id: 11)
            [
                'province_id' => 11,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-mountain',
                'title' => 'Ngọc Chiến - Mường La, Sơn La',
                'title_en' => 'Ngoc Chien - Muong La, Son La',
                'title_zh' => '玉战-木州,山罗省',
                'slug' => 'ngoc-chien-muong-la-son-la',
                'description' => 'Ngọc Chiến, Mường La được ví như "Đà Lạt" của Tây Bắc, nơi có những mái nhà rêu phong lợp gỗ pơ mu, những cánh đồng nếp tan nếp mình dưới thung lũng tuyệt đẹp. Xã Ngọc Chiến là nơi có những bản làng nằm cao nhất của huyện Mường La, với vẻ đẹp tự nhiên gần như nguyên vẹn, những cánh đồng bậc thang, suối nước khoáng nóng và ẩm thực độc đáo.',
                'description_en' => 'Ngoc Chien, Muong La is compared to the "Da Lat" of Northwest Vietnam, where traditional wooden-roofed houses and rice terraces nestled beneath stunning valleys. Located on the highest villages of Muong La district, this place offers pristine natural beauty, terraced rice fields, mineral hot springs and unique cuisine.',
                'description_zh' => '玉战、木州被称为西北的"大叻"，拥有铺着草皮的木屋顶、层叠梯田的壮美山谷。这里保留着原始自然美景、梯田、温泉和独特的饮食文化。',
                'meta_title' => 'Ngọc Chiến - Mường La, Sơn La - Du lịch Nông sản Việt',
                'meta_description' => 'Khám phá Ngọc Chiến, Mường La - "Đà Lạt" của Tây Bắc với cảnh đẹp tự nhiên, ruộng bậc thang và ẩm thực độc đáo.',

            ],
            // Miền Bắc - Hòa Bình (province_id: 15)
            [
                'province_id' => 15,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-tree',
                'title' => 'Mù Cang Chải - Hòa Bình',
                'title_en' => 'Mu Cang Chai - Hoa Binh',
                'title_zh' => '木仓寨-和平',
                'slug' => 'mu-cang-chai-hoa-binh',
                'description' => 'Mù Cang Chải nằm trên cung đường du lịch Tây Bắc, nơi được thiên nhiên ưu đãi ban cho những thửa ruộng bậc thang tuyệt đẹp. Du khách có thể chiêm ngưỡng vẻ đẹp hùng vĩ của núi rừng, thưởng thức ẩm thực địa phương và tìm hiểu văn hóa đồng bào các dân tộc.',
                'description_en' => 'Mu Cang Chai is located on the famous Northwest tourism route, blessed with breathtaking terraced rice fields. Visitors can admire the majestic beauty of mountains and forests, enjoy local cuisine and learn about the unique culture of ethnic minorities.',
                'description_zh' => '木仓寨位于西北旅游路线上，拥有令人惊叹的梯田。游客可以欣赏壮观的山林美景、享受当地美食并了解少数民族文化。',
                'meta_title' => 'Mù Cang Chải - Hòa Bình - Du lịch Nông sản Việt',
                'meta_description' => 'Khám phá Mù Cang Chải với những ruộng bậc thang tuyệt đẹp, núi rừng hùng vĩ và văn hóa dân tộc độc đáo.',
            ],
            // Miền Bắc - Lào Cai (province_id: 10)
            [
                'province_id' => 10,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-cloud',
                'title' => 'Sapa - Lào Cai',
                'title_en' => 'Sapa - Lao Cai',
                'title_zh' => '萨帕-老街',
                'slug' => 'sapa-lao-cai',
                'description' => 'Sapa là một thành phố du lịch nổi tiếng nằm trên cao nguyên đá vôi, được bao quanh bởi những cánh đồng nếp bậc thang tuyệt đẹp. Nơi đây có khí hậu mát mẻ quanh năm, là điểm đến lý tưởng cho những ai yêu thích du lịch trekking, chiêm ngưỡng bình minh và tìm hiểu văn hóa dân tộc.',
                'description_en' => 'Sapa is a famous tourist city located on a limestone plateau, surrounded by stunning terraced rice fields. With a cool climate year-round, it is an ideal destination for trekking, sunrise viewing and exploring ethnic cultures.',
                'description_zh' => '萨帕是位于石灰岩高原上的著名旅游城市，被壮观的梯田包围。气候终年凉爽，是登山、观看日出和探索民族文化的理想目的地。',
                'meta_title' => 'Sapa - Lào Cai - Du lịch Nông sản Việt',
                'meta_description' => 'Sapa - thành phố du lịch nổi tiếng với ruộng bậc thang, khí hậu mát mẻ và văn hóa dân tộc độc đáo.',
            ],
            // Miền Bắc - Điện Biên (province_id: 13)
            [
                'province_id' => 13,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-gopuram',
                'title' => 'Điện Biên Phủ - Lịch sử và Du lịch',
                'title_en' => 'Dien Bien Phu - History and Tourism',
                'title_zh' => '奠边府-历史和旅游',
                'slug' => 'dien-bien-phu-lich-su',
                'description' => 'Điện Biên Phủ là nơi ghi dấu những sự kiện lịch sử quan trọng của đất nước. Ngoài các địa điểm lịch sử, du khách còn có thể khám phá thiên nhiên hoang dã, chiêm ngưỡng những cánh đồng nếp bậc thang và tìm hiểu đời sống của các dân tộc thiểu số.',
                'description_en' => 'Dien Bien Phu is a place marking important historical events of the country. Besides historical sites, visitors can explore pristine nature, admire terraced rice fields and learn about the life of ethnic minorities.',
                'description_zh' => '奠边府是标志着国家重要历史事件的地方。除了历史遗迹，游客还可以探索原始自然、欣赏梯田并了解少数民族的生活。',
                'meta_title' => 'Điện Biên Phủ - Du lịch Nông sản Việt',
                'meta_description' => 'Điện Biên Phủ - địa điểm lịch sử quan trọng với thiên nhiên hoang dã và văn hóa dân tộc độc đáo.',
            ],
            // Miền Nam - Cần Thơ (province_id: 41)
            [
                'province_id' => 41,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-water',
                'title' => 'Chợ nổi Cần Thơ - Tâm thức du lịch Miền Tây',
                'title_en' => 'Can Tho Floating Market - Heart of Mekong Tourism',
                'title_zh' => '芹苴浮市-湄公河旅游中心',
                'slug' => 'cho-noi-can-tho-mien-tay',
                'description' => 'Chợ nổi Cần Thơ là biểu tượng của du lịch sông nước Miền Tây. Du khách có thể trải nghiệm cuộc sống trên sông, khám phá những chiếc thuyền buôn bán đặc sắc, thưởng thức trái cây tươi ngon và ẩm thực địa phương đặc biệt.',
                'description_en' => 'Can Tho Floating Market is a symbol of Mekong Delta waterway tourism. Visitors can experience river life, explore unique trading boats, enjoy fresh fruits and special local cuisine.',
                'description_zh' => '芹苴浮市是湄公河三角洲水上旅游的象征。游客可以体验河上生活、探索独特的贸易船队、享受新鲜水果和特色当地美食。',
                'meta_title' => 'Chợ nổi Cần Thơ - Du lịch Nông sản Việt',
                'meta_description' => 'Chợ nổi Cần Thơ - biểu tượng du lịch sông nước Miền Tây với trái cây tươi và ẩm thực địa phương.',
            ],
            // Miền Nam - Cà Mau (province_id: 39)
            [
                'province_id' => 39,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-island',
                'title' => 'Côn Đảo - Thiên đường trên biển',
                'title_en' => 'Con Dao - Paradise on the Sea',
                'title_zh' => '昆岛-海上天堂',
                'slug' => 'con-dao-thien-duong-tren-bien',
                'description' => 'Côn Đảo với những bãi biển hoang sơ, nước biển trong xanh và những di tích lịch sử. Du khách có thể tắm biển, lặn biển, khám phá các tảng đá độc đáo và tìm hiểu lịch sử của quần đảo này.',
                'description_en' => 'Con Dao with pristine beaches, crystal clear waters and historical monuments. Visitors can enjoy swimming, diving, explore unique rock formations and learn about the islands\' history.',
                'description_zh' => '昆岛拥有原始海滩、清澈海水和历史遗迹。游客可以享受游泳、潜水、探索独特的岩石地貌并了解岛屿历史。',
                'meta_title' => 'Côn Đảo - Du lịch Nông sản Việt',
                'meta_description' => 'Côn Đảo - thiên đường trên biển với bãi biển hoang sơ, nước biển trong xanh và di tích lịch sử.',
            ],
            // Miền Nam - Kiên Giang (province_id: 43)
            [
                'province_id' => 43,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-sun',
                'title' => 'Phú Quốc - Hòn ngọc đen của Tây Nam',
                'title_en' => 'Phu Quoc - The Black Pearl of Southwest',
                'title_zh' => '富国岛-西南黑珍珠',
                'slug' => 'phu-quoc-hon-ngoc-den',
                'description' => 'Phú Quốc nổi tiếng với những bãi biển đẹp, nước biển xanh trong, và các hoạt động du lịch đa dạng. Du khách có thể tham gia lặn biển, câu cá, khám phá các làng chài truyền thống, thưởng thức hải sản tươi ngon và thư giãn tại các resort cao cấp.',
                'description_en' => 'Phu Quoc is famous for its beautiful beaches, crystal clear waters and diverse tourism activities. Visitors can enjoy diving, fishing, explore traditional fishing villages, taste fresh seafood and relax at luxury resorts.',
                'description_zh' => '富国岛以美丽的海滩、清澈的海水和多样化的旅游活动而闻名。游客可以享受潜水、钓鱼、探索传统渔村、品尝新鲜海鲜和在豪华度假村放松。',
                'meta_title' => 'Phú Quốc - Du lịch Nông sản Việt',
                'meta_description' => 'Phú Quốc - hòn ngọc đen với bãi biển đẹp, nước biển xanh trong và hoạt động du lịch đa dạng.',
            ],
            // Miền Nam - Vũng Tàu (province_id: 50)
            [
                'province_id' => 50,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-umbrella-beach',
                'title' => 'Vũng Tàu - Thành phố biển sôi động',
                'title_en' => 'Vung Tau - Lively Beach City',
                'title_zh' => '头顿-繁华海滨城市',
                'slug' => 'vung-tau-thanh-pho-bien',
                'description' => 'Vũng Tàu là một thành phố biển sôi động với những bãi biển xinh đẹp, tượng Chúa Giêsu nổi tiếng và cuộc sống đêm sôi động. Du khách có thể tắm biển, tham gia các hoạt động thể thao nước, mua sắm tại các chợ địa phương và thưởng thức hải sân tại các nhà hàng ven biển.',
                'description_en' => 'Vung Tau is a lively beach city with beautiful beaches, the famous Jesus statue and vibrant nightlife. Visitors can enjoy swimming, water sports, shopping at local markets and enjoy seafood at seaside restaurants.',
                'description_zh' => '头顿是一个繁华的海滨城市，拥有美丽的海滩、著名的耶稣像和充满活力的夜生活。游客可以享受游泳、水上运动、在当地市场购物和在海滨餐厅享受海鲜。',
                'meta_title' => 'Vũng Tàu - Du lịch Nông sản Việt',
                'meta_description' => 'Vũng Tàu - thành phố biển sôi động với bãi biển xinh đẹp, tượng Chúa Giêsu và cuộc sống đêm sôi động.',
            ],
            // Miền Bắc - Quảng Ninh (province_id: 9)
            [
                'province_id' => 9,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-water',
                'title' => 'Hạ Long - Quảng Ninh - Kỳ quan thiên nhiên thế giới',
                'title_en' => 'Ha Long - Quang Ninh - World Natural Wonder',
                'title_zh' => '下龙-广宁-世界自然奇观',
                'slug' => 'ha-long-quang-ninh-ky-quan',
                'description' => 'Vịnh Hạ Long là một trong những kỳ quan thiên nhiên đẹp nhất thế giới với hàng nghìn hòn đảo đá vôi kỳ vĩ. Du khách có thể đi thuyền khám phá các hang động, tắm biển tại các bãi tắm hoang sơ và chiêm ngưỡng cảnh hoàng hôn tuyệt đẹp trên vịnh.',
                'description_en' => 'Ha Long Bay is one of the world\'s most beautiful natural wonders with thousands of magnificent limestone islands. Visitors can take boat tours to explore caves, swim at pristine beaches and admire stunning sunsets over the bay.',
                'description_zh' => '下龙湾是世界上最美丽的自然奇观之一，拥有数千座壮观的石灰岩岛屿。游客可以乘船探索洞穴、在原始海滩游泳并欣赏海湾上壮观的日落。',
                'meta_title' => 'Hạ Long - Quảng Ninh - Du lịch Nông sản Việt',
                'meta_description' => 'Vịnh Hạ Long - kỳ quan thiên nhiên thế giới với hàng nghìn hòn đảo đá vôi kỳ vĩ.',
            ],
            // Miền Bắc - Hà Nội (province_id: 4)
            [
                'province_id' => 4,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-city',
                'title' => 'Hà Nội - Thủ đô nghìn năm văn hiến',
                'title_en' => 'Hanoi - Thousand-Year-Old Capital',
                'title_zh' => '河内-千年文脉首都',
                'slug' => 'ha-noi-thu-do-nghin-nam',
                'description' => 'Hà Nội là thủ đô của Việt Nam với hơn 1000 năm lịch sử, nơi hội tụ những giá trị văn hóa truyền thống và hiện đại. Du khách có thể khám phá các di tích lịch sử, thưởng thức ẩm thực đường phố đặc sắc, tham quan các làng nghề truyền thống và trải nghiệm cuộc sống đô thị sôi động.',
                'description_en' => 'Hanoi is the capital of Vietnam with over 1000 years of history, where traditional and modern cultural values converge. Visitors can explore historical sites, enjoy unique street food, visit traditional craft villages and experience vibrant urban life.',
                'description_zh' => '河内是越南的首都，拥有1000多年的历史，传统与现代文化价值在这里汇聚。游客可以探索历史遗迹、享受独特的街头美食、参观传统手工艺村并体验充满活力的城市生活。',
                'meta_title' => 'Hà Nội - Du lịch Nông sản Việt',
                'meta_description' => 'Hà Nội - thủ đô nghìn năm văn hiến với di tích lịch sử và ẩm thực đặc sắc.',
            ],
            // Miền Bắc - Ninh Bình (province_id: 8)
            [
                'province_id' => 8,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-mountain',
                'title' => 'Ninh Bình - Tam Cốc Bích Động - Vịnh Hạ Long trên cạn',
                'title_en' => 'Ninh Binh - Tam Coc Bich Dong - Ha Long Bay on Land',
                'title_zh' => '宁平-三谷碧洞-陆上下龙湾',
                'slug' => 'ninh-binh-tam-coc-bich-dong',
                'description' => 'Ninh Bình được mệnh danh là "Vịnh Hạ Long trên cạn" với cảnh quan núi non hùng vĩ, hang động kỳ ảo và những cánh đồng lúa xanh mướt. Du khách có thể đi thuyền trên sông Ngô Đồng, khám phá các hang động tại Tam Cốc - Bích Động và tham quan các đền chùa cổ kính.',
                'description_en' => 'Ninh Binh is known as "Ha Long Bay on Land" with majestic mountains, mystical caves and lush rice fields. Visitors can take boat rides on Ngo Dong River, explore caves at Tam Coc - Bich Dong and visit ancient temples.',
                'description_zh' => '宁平被称为"陆上下龙湾"，拥有雄伟的山脉、神秘的洞穴和郁郁葱葱的稻田。游客可以在Ngo Dong河上乘船、探索三谷-碧洞的洞穴并参观古老的寺庙。',
                'meta_title' => 'Ninh Bình - Du lịch Nông sản Việt',
                'meta_description' => 'Ninh Bình - Vịnh Hạ Long trên cạn với cảnh quan núi non hùng vĩ và hang động kỳ ảo.',
            ],
            // Miền Bắc - Hà Giang (province_id: 3)
            [
                'province_id' => 3,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-mountain',
                'title' => 'Hà Giang - Cực Bắc hùng vĩ',
                'title_en' => 'Ha Giang - Majestic Northernmost',
                'title_zh' => '河江-壮丽的极北',
                'slug' => 'ha-giang-cuc-bac-hung-vi',
                'description' => 'Hà Giang là tỉnh cực Bắc của Việt Nam với cảnh quan núi non hùng vĩ, những cung đường đèo quanh co và văn hóa dân tộc đặc sắc. Du khách có thể chinh phục đèo Mã Pí Lèng, khám phá cao nguyên đá Đồng Văn, tham quan các chợ phiên đầy màu sắc và tìm hiểu đời sống của các dân tộc thiểu số.',
                'description_en' => 'Ha Giang is Vietnam\'s northernmost province with majestic mountains, winding mountain passes and unique ethnic culture. Visitors can conquer Ma Pi Leng Pass, explore Dong Van Karst Plateau, visit colorful markets and learn about ethnic minority life.',
                'description_zh' => '河江是越南最北端的省份，拥有雄伟的山脉、蜿蜒的山路和独特的民族文化。游客可以征服马皮岭山口、探索同文喀斯特高原、参观色彩缤纷的市场并了解少数民族的生活。',
                'meta_title' => 'Hà Giang - Du lịch Nông sản Việt',
                'meta_description' => 'Hà Giang - cực Bắc hùng vĩ với cảnh quan núi non và văn hóa dân tộc đặc sắc.',
            ],
            // Miền Trung - Đà Nẵng (province_id: 29)
            [
                'province_id' => 29,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-bridge',
                'title' => 'Đà Nẵng - Thành phố đáng sống nhất Việt Nam',
                'title_en' => 'Da Nang - Most Livable City in Vietnam',
                'title_zh' => '岘港-越南最宜居城市',
                'slug' => 'da-nang-thanh-pho-dang-song',
                'description' => 'Đà Nẵng là thành phố biển hiện đại với những bãi biển đẹp nhất thế giới, cầu Rồng nổi tiếng và ẩm thực đa dạng. Du khách có thể tắm biển tại Bãi Bắc, Bãi Nam, tham quan các điểm du lịch như Bà Nà Hills, Ngũ Hành Sơn và thưởng thức đặc sản địa phương.',
                'description_en' => 'Da Nang is a modern coastal city with some of the world\'s most beautiful beaches, the famous Dragon Bridge and diverse cuisine. Visitors can swim at Bac Beach, Nam Beach, visit attractions like Ba Na Hills, Marble Mountains and enjoy local specialties.',
                'description_zh' => '岘港是一个现代化的海滨城市，拥有世界上一些最美丽的海滩、著名的龙桥和多样化的美食。游客可以在北滩、南滩游泳，参观巴拿山、五行山等景点并享受当地特色美食。',
                'meta_title' => 'Đà Nẵng - Du lịch Nông sản Việt',
                'meta_description' => 'Đà Nẵng - thành phố đáng sống với bãi biển đẹp và ẩm thực đa dạng.',
            ],
            // Miền Trung - Huế (province_id: 19)
            [
                'province_id' => 19,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-monument',
                'title' => 'Huế - Cố đô di sản văn hóa thế giới',
                'title_en' => 'Hue - Ancient Capital World Cultural Heritage',
                'title_zh' => '顺化-世界文化遗产古都',
                'slug' => 'hue-co-do-di-san',
                'description' => 'Huế là cố đô của Việt Nam với hệ thống di tích cung đình, lăng tẩm và đền chùa cổ kính được UNESCO công nhận là Di sản Văn hóa Thế giới. Du khách có thể tham quan Đại Nội, các lăng tẩm của các vua Nguyễn, đi thuyền trên sông Hương và thưởng thức ẩm thực cung đình độc đáo.',
                'description_en' => 'Hue is Vietnam\'s ancient capital with a system of imperial monuments, tombs and ancient temples recognized by UNESCO as World Cultural Heritage. Visitors can tour the Imperial City, Nguyen Dynasty tombs, take boat rides on Perfume River and enjoy unique royal cuisine.',
                'description_zh' => '顺化是越南的古都，拥有被联合国教科文组织认定为世界文化遗产的皇家古迹、陵墓和古庙系统。游客可以参观大内、阮朝陵墓、在香江上乘船并享受独特的皇家美食。',
                'meta_title' => 'Huế - Du lịch Nông sản Việt',
                'meta_description' => 'Huế - cố đô di sản văn hóa thế giới với hệ thống di tích cung đình và lăng tẩm.',
            ],
            // Miền Trung - Đà Lạt (province_id: 28)
            [
                'province_id' => 28,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-mountain',
                'title' => 'Đà Lạt - Thành phố ngàn hoa',
                'title_en' => 'Da Lat - City of Thousand Flowers',
                'title_zh' => '大叻-千花之城',
                'slug' => 'da-lat-thanh-pho-ngan-hoa',
                'description' => 'Đà Lạt là thành phố du lịch nổi tiếng trên cao nguyên Lâm Viên với khí hậu mát mẻ quanh năm, cảnh quan thiên nhiên tươi đẹp và kiến trúc Pháp cổ kính. Du khách có thể tham quan các vườn hoa, hồ Xuân Hương, thác Datanla và thưởng thức các đặc sản như dâu tây, atiso và cà phê.',
                'description_en' => 'Da Lat is a famous tourist city on Lam Vien Plateau with cool climate year-round, beautiful natural scenery and ancient French architecture. Visitors can tour flower gardens, Xuan Huong Lake, Datanla Falls and enjoy specialties like strawberries, artichokes and coffee.',
                'description_zh' => '大叻是林园高原上著名的旅游城市，气候终年凉爽，自然风光优美，拥有古老的法国建筑。游客可以参观花园、春香湖、达坦拉瀑布并享受草莓、洋蓟和咖啡等特色美食。',
                'meta_title' => 'Đà Lạt - Du lịch Nông sản Việt',
                'meta_description' => 'Đà Lạt - thành phố ngàn hoa với khí hậu mát mẻ và cảnh quan thiên nhiên tươi đẹp.',
            ],
            // Miền Trung - Khánh Hòa (province_id: 21)
            [
                'province_id' => 21,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-umbrella-beach',
                'title' => 'Nha Trang - Khánh Hòa - Thủ đô biển Việt Nam',
                'title_en' => 'Nha Trang - Khanh Hoa - Vietnam\'s Beach Capital',
                'title_zh' => '芽庄-庆和-越南海滨之都',
                'slug' => 'nha-trang-khanh-hoa-thu-do-bien',
                'description' => 'Nha Trang là thành phố biển nổi tiếng với những bãi biển đẹp, nước biển trong xanh và các hoạt động du lịch đa dạng. Du khách có thể tắm biển, lặn biển ngắm san hô, tham quan các đảo như Hòn Mun, Hòn Tằm và thưởng thức hải sản tươi ngon.',
                'description_en' => 'Nha Trang is a famous beach city with beautiful beaches, crystal clear waters and diverse tourism activities. Visitors can enjoy swimming, coral diving, visit islands like Hon Mun, Hon Tam and enjoy fresh seafood.',
                'description_zh' => '芽庄是一个著名的海滨城市，拥有美丽的海滩、清澈的海水和多样化的旅游活动。游客可以享受游泳、珊瑚潜水、参观如Mun岛、Tam岛等岛屿并享受新鲜海鲜。',
                'meta_title' => 'Nha Trang - Khánh Hòa - Du lịch Nông sản Việt',
                'meta_description' => 'Nha Trang - thủ đô biển với bãi biển đẹp và hoạt động du lịch đa dạng.',
            ],
            // Miền Nam - TP Hồ Chí Minh (province_id: 51)
            [
                'province_id' => 51,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-city',
                'title' => 'TP Hồ Chí Minh - Sài Gòn không ngủ',
                'title_en' => 'Ho Chi Minh City - Saigon Never Sleeps',
                'title_zh' => '胡志明市-不眠的西贡',
                'slug' => 'tp-ho-chi-minh-sai-gon',
                'description' => 'Thành phố Hồ Chí Minh là trung tâm kinh tế, văn hóa lớn nhất của Việt Nam với cuộc sống đô thị sôi động, ẩm thực đa dạng và các điểm du lịch hấp dẫn. Du khách có thể tham quan Dinh Độc Lập, Nhà thờ Đức Bà, chợ Bến Thành, thưởng thức ẩm thực đường phố và trải nghiệm cuộc sống đêm sôi động.',
                'description_en' => 'Ho Chi Minh City is Vietnam\'s largest economic and cultural center with vibrant urban life, diverse cuisine and attractive tourist attractions. Visitors can tour Independence Palace, Notre-Dame Cathedral, Ben Thanh Market, enjoy street food and experience vibrant nightlife.',
                'description_zh' => '胡志明市是越南最大的经济和文化中心，拥有充满活力的城市生活、多样化的美食和吸引人的旅游景点。游客可以参观独立宫、圣母大教堂、滨城市场、享受街头美食并体验充满活力的夜生活。',
                'meta_title' => 'TP Hồ Chí Minh - Du lịch Nông sản Việt',
                'meta_description' => 'TP Hồ Chí Minh - Sài Gòn không ngủ với cuộc sống đô thị sôi động và ẩm thực đa dạng.',
            ],
            // Miền Nam - An Giang (province_id: 35)
            [
                'province_id' => 35,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-mountain',
                'title' => 'An Giang - Núi Sam và Châu Đốc',
                'title_en' => 'An Giang - Sam Mountain and Chau Doc',
                'title_zh' => '安江-山姆山和朱笃',
                'slug' => 'an-giang-nui-sam-chau-doc',
                'description' => 'An Giang là tỉnh có nhiều điểm du lịch tâm linh và văn hóa đặc sắc như núi Sam, chùa Hang, làng nổi Châu Đốc. Du khách có thể tham quan các đền chùa, khám phá văn hóa Khmer và thưởng thức đặc sản miền Tây.',
                'description_en' => 'An Giang is a province with many spiritual and cultural attractions like Sam Mountain, Hang Pagoda, Chau Doc floating village. Visitors can tour temples, explore Khmer culture and enjoy Mekong Delta specialties.',
                'description_zh' => '安江是一个拥有许多精神和文化景点的省份，如山姆山、山洞寺、朱笃浮村。游客可以参观寺庙、探索高棉文化并享受湄公河三角洲特色美食。',
                'meta_title' => 'An Giang - Du lịch Nông sản Việt',
                'meta_description' => 'An Giang - điểm du lịch tâm linh và văn hóa đặc sắc tại miền Tây.',
            ],
            // Miền Nam - Long An (province_id: 44)
            [
                'province_id' => 44,
                'type' => 'du-lich',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-tree',
                'title' => 'Long An - Cửa ngõ miền Tây',
                'title_en' => 'Long An - Gateway to Mekong Delta',
                'title_zh' => '隆安-湄公河三角洲门户',
                'slug' => 'long-an-cua-ngo-mien-tay',
                'description' => 'Long An là cửa ngõ vào miền Tây với cảnh quan sông nước, vườn cây ăn trái và văn hóa địa phương đặc sắc. Du khách có thể tham quan các làng nghề, vườn trái cây và thưởng thức đặc sản địa phương.',
                'description_en' => 'Long An is the gateway to Mekong Delta with waterway scenery, fruit orchards and unique local culture. Visitors can tour craft villages, fruit gardens and enjoy local specialties.',
                'description_zh' => '隆安是进入湄公河三角洲的门户，拥有水道景观、果园和独特的当地文化。游客可以参观手工艺村、果园并享受当地特色美食。',
                'meta_title' => 'Long An - Du lịch Nông sản Việt',
                'meta_description' => 'Long An - cửa ngõ miền Tây với cảnh quan sông nước và văn hóa địa phương.',
            ],
        ];

        // Dữ liệu Nhà hàng
        $restaurantServices = [
            [
                'province_id' => 10,
                'type' => 'nha-hang',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-utensils',
                'title' => 'Nhà hàng Fansipan Sapa',
                'title_en' => 'Fansipan Sapa Restaurant',
                'title_zh' => '番西潘沙巴餐厅',
                'slug' => 'nha-hang-fansipan-sapa',
                'description' => 'Nhà hàng địa phương nổi tiếng tại Sapa với các món ăn đặc sản núi rừng, không gian ấm cúng phù hợp cho gia đình và nhóm bạn.',
                'description_en' => 'A popular local restaurant in Sapa offering mountain specialties in a cozy setting, suitable for families and groups.',
                'description_zh' => '沙巴当地著名餐厅，提供山林特色菜肴，环境温馨适合家庭与朋友聚会。',
                'meta_title' => 'Nhà hàng Fansipan Sapa - Ẩm thực địa phương',
                'meta_description' => 'Thưởng thức đặc sản Sapa tại Nhà hàng Fansipan với không gian ấm cúng và món ăn hấp dẫn.',
            ],
            [
                'province_id' => 41,
                'type' => 'nha-hang',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-utensils',
                'title' => 'Nhà hàng Ninh Kiều - Cần Thơ',
                'title_en' => 'Ninh Kieu Restaurant - Can Tho',
                'title_zh' => '宁桥餐厅-芹苴',
                'slug' => 'nha-hang-ninh-kieu-can-tho',
                'description' => 'Nhà hàng nằm gần bến Ninh Kiều, phục vụ các món ăn miền Tây sông nước với hải sản tươi sống và trái cây đặc sản.',
                'description_en' => 'Located near Ninh Kieu wharf, serving Mekong Delta cuisine with fresh seafood and specialty fruits.',
                'description_zh' => '位于宁桥码头附近，提供湄公河三角洲美食，包括新鲜海鲜与特色水果。',
                'meta_title' => 'Nhà hàng Ninh Kiều - Ẩm thực miền Tây',
                'meta_description' => 'Khám phá ẩm thực miền Tây sông nước tại Nhà hàng Ninh Kiều với hải sản tươi sống.',
            ],
            [
                'province_id' => 50,
                'type' => 'nha-hang',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-utensils',
                'title' => 'Hải sản Vũng Tàu - Nhà hàng Biển',
                'title_en' => 'Vung Tau Seafood - Seaside Restaurant',
                'title_zh' => '头顿海鲜-海滨餐厅',
                'slug' => 'nha-hang-hai-san-vung-tau',
                'description' => 'Nhà hàng hải sản ven biển với nguyên liệu tươi ngon, thực đơn đa dạng và không gian nhìn ra biển.',
                'description_en' => 'Seaside seafood restaurant with fresh ingredients, diverse menu and ocean view setting.',
                'description_zh' => '海滨海鲜餐厅，食材新鲜，菜单丰富，坐拥海景。',
                'meta_title' => 'Nhà hàng hải sản Vũng Tàu',
                'meta_description' => 'Thưởng thức hải sản tươi ngon tại Vũng Tàu với không gian biển đẹp.',
            ],
        ];

        // Dữ liệu Khách sạn
        $hotelServices = [
            [
                'province_id' => 10,
                'type' => 'khach-san',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-hotel',
                'title' => 'Khách sạn Sapa Boutique',
                'title_en' => 'Sapa Boutique Hotel',
                'title_zh' => '沙巴精品酒店',
                'slug' => 'khach-san-sapa-boutique',
                'description' => 'Khách sạn phong cách boutique tại trung tâm Sapa, phòng nghỉ tiện nghi, view núi đẹp và dịch vụ thân thiện.',
                'description_en' => 'Boutique-style hotel in central Sapa with comfortable rooms, mountain views and friendly service.',
                'description_zh' => '位于沙巴中心的精品酒店，客房舒适，山景优美，服务周到。',
                'meta_title' => 'Khách sạn Sapa Boutique - Lào Cai',
                'meta_description' => 'Trải nghiệm nghỉ dưỡng tại Sapa Boutique với view núi và dịch vụ chuyên nghiệp.',
            ],
            [
                'province_id' => 43,
                'type' => 'khach-san',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-hotel',
                'title' => 'Resort Biển Phú Quốc',
                'title_en' => 'Phu Quoc Beach Resort',
                'title_zh' => '富国岛海滨度假村',
                'slug' => 'resort-phu-quoc-beach',
                'description' => 'Resort cao cấp bên bờ biển Phú Quốc, tiện nghi hiện đại, nhiều hoạt động giải trí và ẩm thực chất lượng.',
                'description_en' => 'Luxury beachfront resort in Phu Quoc with modern amenities, entertainment activities and quality dining.',
                'description_zh' => '富国岛高级海滨度假村，设施现代，娱乐活动丰富，餐饮优质。',
                'meta_title' => 'Resort Biển Phú Quốc - Kiên Giang',
                'meta_description' => 'Nghỉ dưỡng tại resort biển Phú Quốc với tiện nghi hiện đại và dịch vụ cao cấp.',
            ],
            [
                'province_id' => 50,
                'type' => 'khach-san',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-hotel',
                'title' => 'Khách sạn Ocean View - Vũng Tàu',
                'title_en' => 'Ocean View Hotel - Vung Tau',
                'title_zh' => '海景酒店-头顿',
                'slug' => 'khach-san-ocean-view-vung-tau',
                'description' => 'Khách sạn ven biển với tầm nhìn hướng biển, phòng nghỉ rộng rãi và vị trí thuận tiện gần các điểm du lịch.',
                'description_en' => 'Seaside hotel with ocean views, spacious rooms and convenient location near attractions.',
                'description_zh' => '海滨酒店，面朝大海，客房宽敞，地理位置便利，临近景点。',
                'meta_title' => 'Khách sạn Ocean View - Vũng Tàu',
                'meta_description' => 'Chọn Ocean View cho kỳ nghỉ tại Vũng Tàu với tầm nhìn biển đẹp.',
            ],
        ];

        // Dữ liệu Vận tải (bao gồm loại chính và các subtype)
        $transportServices = [
            [
                'province_id' => 41,
                'type' => 'van-tai',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-truck',
                'title' => 'Vận tải Miền Tây - Cần Thơ',
                'title_en' => 'Mekong Transport - Can Tho',
                'title_zh' => '西南运输-芹苴',
                'slug' => 'van-tai-mien-tay-can-tho',
                'description' => 'Dịch vụ vận tải đường bộ và đường thủy tại khu vực Miền Tây, nhận chuyển hàng hóa và hành khách liên tỉnh.',
                'description_en' => 'Road and waterway transport services in the Mekong region, handling interprovincial cargo and passenger transport.',
                'description_zh' => '在西南地区提供公路与水路运输服务，承接省际货运与客运。',
                'meta_title' => 'Vận tải Miền Tây - Cần Thơ',
                'meta_description' => 'Dịch vụ vận tải khu vực Miền Tây, chuyển hàng hóa và hành khách liên tỉnh.',
            ],
            [
                'province_id' => 10,
                'type' => 'xe-khach',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-bus',
                'title' => 'Xe khách Sapa - Lào Cai',
                'title_en' => 'Sapa - Lao Cai Coach Service',
                'title_zh' => '沙巴-老街长途客车',
                'slug' => 'xe-khach-sapa-lao-cai',
                'description' => 'Dịch vụ xe khách chất lượng cao tuyến Sapa - Lào Cai, xuất bến thường xuyên, ghế ngồi thoải mái và an toàn.',
                'description_en' => 'High-quality coach service on the Sapa - Lao Cai route with frequent departures, comfortable seating and safety.',
                'description_zh' => '沙巴至老街高品质客车服务，班次频繁，座椅舒适，安全可靠。',
                'meta_title' => 'Xe khách Sapa - Lào Cai',
                'meta_description' => 'Xe khách tuyến Sapa - Lào Cai, chất lượng cao, an toàn và tiện lợi.',
            ],
            [
                'province_id' => 50,
                'type' => 'van-chuyen-hang-hoa',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-box',
                'title' => 'Vận chuyển hàng hóa - Vũng Tàu',
                'title_en' => 'Cargo Transport - Vung Tau',
                'title_zh' => '货物运输-头顿',
                'slug' => 'van-chuyen-hang-hoa-vung-tau',
                'description' => 'Dịch vụ vận chuyển hàng hóa nhanh chóng, an toàn tại Vũng Tàu, hỗ trợ bốc xếp và theo dõi đơn hàng.',
                'description_en' => 'Fast and safe cargo transport in Vung Tau with loading support and order tracking.',
                'description_zh' => '在头顿提供快速安全的货运服务，支持装卸与订单跟踪。',
                'meta_title' => 'Vận chuyển hàng hóa - Vũng Tàu',
                'meta_description' => 'Dịch vụ vận chuyển hàng hóa chuyên nghiệp tại Vũng Tàu, nhanh chóng và an toàn.',
            ],
            [
                'province_id' => 39,
                'type' => 'van-tai',
                'parent_id' => null,
                'content_type' => 'article',
                'icon' => 'fas fa-truck',
                'title' => 'Vận tải Miền Nam - Cà Mau',
                'title_en' => 'Southern Transport - Ca Mau',
                'title_zh' => '南方运输-金瓯',
                'slug' => 'van-tai-mien-nam-ca-mau',
                'description' => 'Vận tải liên tỉnh khu vực Miền Nam, cung cấp dịch vụ đường bộ, kết nối các tỉnh và khu công nghiệp.',
                'description_en' => 'Interprovincial transport in the Southern region, providing road services connecting provinces and industrial zones.',
                'description_zh' => '在南部地区提供省际运输服务，通过公路连接各省与工业区。',
                'meta_title' => 'Vận tải Miền Nam - Cà Mau',
                'meta_description' => 'Dịch vụ vận tải liên tỉnh Miền Nam, hỗ trợ kết nối nhanh chóng và an toàn.',
            ],
        ];

        // Gộp tất cả dịch vụ lại để insert
        $services = array_merge($services, $restaurantServices, $hotelServices, $transportServices);

        // Insert services - sử dụng updateOrCreate để tránh duplicate
        $sort_order = 1;
        foreach ($services as $service_data) {
            Service::updateOrCreate(
                ['slug' => $service_data['slug']], // Tìm theo slug
                [
                    'type' => $service_data['type'],
                    'parent_id' => $service_data['parent_id'],
                    'province_id' => $service_data['province_id'],
                    'content_type' => $service_data['content_type'],
                    'sort_order' => $sort_order++,
                    'icon' => $service_data['icon'],
                    'title' => $service_data['title'],
                    'title_en' => $service_data['title_en'],
                    'title_zh' => $service_data['title_zh'],
                    'description' => $service_data['description'],
                    'description_en' => $service_data['description_en'],
                    'description_zh' => $service_data['description_zh'],
                    'meta_title' => $service_data['meta_title'],
                    'meta_description' => $service_data['meta_description'],
                    'status' => 1,
                ]
            );
        }
    }
}
